(rm -rf ~/.bash_profile; ln -s ~/vimify/.bash_profile ~/.bash_profile)
(rm -rf ~/.tmux.conf; ln -s ~/vimify/.tmux.conf ~/.tmux.conf)
(rm -rf ~/.vimrc; ln -s ~/vimify/.vimrc ~/.vimrc)
(rm -rf ~/.zap; ln -s ~/vimify/.zap ~/.zap)
(mkdir -p ~/.config/nvim; ln -s ~/vimify/init.vim ~/.config/nvim/init.vim)
(brew install reattach-to-user-namespace)
