(ln -s ~/vimify/.bash_profile ~/.bash_profile)
(ln -s ~/vimify/.tmux.conf ~/.tmux.conf)
(ln -s ~/vimify/.vimrc ~/.vimrc)
(mkdir -p ~/.config/nvim; ln -s ~/vimify/init.vim ~/.config/nvim/init.vim)
(brew install reattach-to-user-namespace)
